name: Verify

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - README.md
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
      - README.md

jobs:
  verify-frontend:
    name: Verify frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: ./frontend/package.json
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.nvmrc
          cache-dependency-path: ./frontend
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run verify
